### ISSUE TITLE
Example Grafana Dashboard?

### ISSUE THREAD

**Issue by DanielWeeber** [treydock/eseries_exporter#21]
Hey,

do you have a grafana dashboard that you would like to share? :)

Thank you very much for the exporter, works nicely!

**Comment by treydock** [comment]
I do not have one. I used this exporter mostly for alerts about E-Series health.

**Comment by DanielWeeber** [comment]
I just created one, but this has to be checked for good measure. Not sure if I did everything correctly
[netapp-eseries-grafana.txt](https://github.com/treydock/eseries_exporter/files/7708013/netapp-eseries-grafana.txt)
.

**Comment by treydock** [comment]
Looks like person in #17 posted some screenshots of their dashboard

**Comment by DanielWeeber** [comment]
<img width="2107" alt="Bildschirmfoto 2021-12-14 um 02 40 58" src="https://user-images.githubusercontent.com/2935130/145917131-acf82411-a837-47dc-bb46-ee0b387d3196.png">

**Comment by DanielWeeber** [comment]
<img width="1644" alt="Bildschirmfoto 2021-12-14 um 02 42 09" src="https://user-images.githubusercontent.com/2935130/145917271-88b83bb8-cccc-4d8f-9277-57b29e260683.png">

**Comment by DanielWeeber** [comment]
Would you mind sharing your alertmanager rules?

**Comment by treydock** [comment]
Added my rules to examples directory: https://github.com/treydock/eseries_exporter/blob/master/examples/alert-rules.yaml
